site_name: Toucan Documentation

nav:
- Home: 'index.md'
- Planning: 'planning/index.md'
- End User Guide:
    - 'Features': 'user-guide/features.md'
- Developers:
    - 'Local Installation': 'developers/local_installation.md'
    - 'Using Docker': 'developers/using-docker.md'
- About: 'about.md'

theme: readthedocs
